apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: {{ required "A namespace must be provided" .Values.namespace }}
data:
  loki-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    schema_config:
      configs:
        - from: 2023-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            type: boltdb-shipper
    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/cache
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks