apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: {{ required "A namespace must be provided" .Values.namespace }}
  labels: { app: loki }
spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels: { app: loki }
  template:
    metadata:
      labels: { app: loki }
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.3            # cố định phiên bản
          ports: [{ containerPort: 3100 }]
          args: [ "-config.file=/etc/loki/loki-config.yaml" ]
          volumeMounts:
            - { name: config, mountPath: /etc/loki }
      volumes:
        - name: config
          configMap: { name: loki-config }