apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: petclinic-error-rate-rules
  namespace: {{ required "A namespace must be provided" .Values.namespace }}
spec:
  groups:
    - name: petclinic.rules
      rules:
        - alert: HighErrorRate
          expr: sum(rate(http_server_requests_seconds_count{status=~"5.."}[30s])) > 10
          for: 30s
          labels:
            severity: critical
          annotations:
            summary: "Error rate > 10 in 30s"
            description: "High number of 5xx responses from Petclinic services"