{{- range $index, $user := .Values.users }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.application.name }}-user-{{ $user }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ $.Values.application.repo.url }}
    targetRevision: HEAD
    path: users/{{ $user }}/
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $user }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---    
{{- end }}