{{- range $index, $user := .Values.users }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.application.name }}-user-{{ $user }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ $.Values.application.repo.url }}
    targetRevision: HEAD
    path: users/{{ $user }}/
    helm:
      valueFiles:
        - values-{{ $user }}.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $user }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
---    
{{- end }}