{{- range $index, $namespace := .Values.application.namespaces }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.application.name }}-{{ $namespace }}
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: >-
      {{- $repo := $.Values.application.image.repository }}
      {{- $ns := $namespace }}
      {{- $first := true }}
      {{- range $i, $name := $.Values.application.image.base }}
        {{- $full := printf "%s-%s" $name $ns }}
        {{- if not $first }},{{ end }}
        {{- $first = false }}
        {{ $full }}={{ $repo }}/spring-petclinic-{{ $full }}
      {{- end }}

    {{- $ns := $namespace }}
    {{- range $i, $name := $.Values.application.image.base }}
      {{- $full := printf "%s-%s" $name $ns }}
    argocd-image-updater.argoproj.io/{{ $full }}.helm-value: tags.{{ $full }}
    argocd-image-updater.argoproj.io/{{ $full }}.update-strategy: newest-build
    argocd-image-updater.argoproj.io/{{ $full }}.pull-secret: "secret:argocd-image-updater/dockerhub-creds#secret"
    {{- end }}
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: "helmvalues:/spring-petclinic/values-{{ $namespace }}.yaml"
    argocd-image-updater.argoproj.io/git-repository: {{ $.Values.application.repo.url }}
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: {{ $.Values.application.repo.url }}
    targetRevision: main
    path: {{ $.Values.application.repo.path }}
    helm:
      valueFiles:
        - values-{{ $namespace }}.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---    
{{- end }}