application:
  name: argocd-app
  repo:
    url: https://github.com/TerryTantan/spring-petclinic-microservices-k8s-config.git
    path: spring-petclinic/
  namespaces:
    - dev
    - staging

users:
  - dev123