application:
  name: argocd-app
  repo:
    url: https://github.com/TerryTantan/spring-petclinic-microservices-k8s-config.git
    applicationPath: argocd-apps/
    path: spring-petclinic/
  namespaces:
    - dev
    - staging
  image:
    repository: terrytantan
    base:
      - config-server
      - discovery-server
      - admin-server
      - api-gateway
      - customers-service
      - genai-service
      - vets-service
      - visits-service

users: