{{- range $index, $namespace := .Values.application.namespaces }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.application.name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ $.Values.application.repo.url }}
    targetRevision: HEAD
    path: {{ $.Values.application.repo.path }}
    helm:
      valueFiles:
        - values-{{ $namespace }}.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---    
{{- end }}