{{- range $i, $server := .Values.servers }}
  {{- range $key, $configInfo := $server }}
{{- $serviceName := $configInfo.appName }}
{{- $envSuffix := "dev" }}
{{- if eq $.Values.namespace "staging" }}
  {{- $envSuffix = "staging" }}
{{- end }}
{{- $serviceKey := print $serviceName "-" $envSuffix }}
{{- $tag := or (index $.Values.tags $serviceKey) (index $.Values.tags (print $serviceName "-" $.Values.namespace)) $.Values.tag "latest" }}
{{- include "spring-petclinic.deployment" (dict "root" $configInfo "namespace" $.Values.namespace "image" $.Values.image "profile" $.Values.profile "tag" $tag)}}
---
{{- end }}
{{- end }}