apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: {{ required "A namespace must be provided" .Values.namespace }}
  labels:
    app: grafana
    config-hash: {{ include (print $.Template.BasePath "/grafana/config.yaml") . | sha256sum | trunc 8 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
      annotations:
        timestamp: {{ now | date "2006-01-02T15:04:05Z07:00" }}
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.2.3 # pinned version
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: datasource-volume
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboard-volume
              mountPath: /etc/grafana/provisioning/dashboards
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.adminPassword | quote }}
      volumes:
        - name: datasource-volume
          configMap:
            name: grafana-datasource-config
        - name: dashboard-volume
          configMap:
            name: grafana-dashboard-config