apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ required "A namespace must be provided" .Values.namespace }}
  labels:
    app: loki
spec:
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP
      name: http
  selector:
    app: loki