apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ required "A namespace must be provided" .Values.namespace }}
  labels:
    app: prometheus
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: prometheus

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: {{ required "A namespace must be provided" .Values.namespace }}
  labels:
    app: alertmanager
spec:
  type: ClusterIP
  ports:
    - port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app: alertmanager

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-discord
  namespace: {{ required "A namespace must be provided" .Values.namespace }}
  labels:
    app: alertmanager-discord
spec:
  type: ClusterIP
  ports:
    - port: 9094
      targetPort: 9094
      protocol: TCP
  selector:
    app: alertmanager-discord