apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ required "A namespace must be provided" .Values.namespace }}
  labels:
    app: grafana
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: grafana