---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-webhook-secret
  namespace: {{ required "A namespace must be provided" .Values.namespace }}
spec:
  encryptedData:
    webhookUrl: AgBhhm8UnuGUvw9VQWXyyi8VcxhN16hQMHHvbnOBEeUZD7rQBBWNiZXfQUUmOurpts+9X0s27jELf83pBbYLGN3eBTlkFEF1OJxcGwb1cN3JeY8iAlldVvTQqcSe0eF1De6tzDfKYkwR1AAkovlGQdvLbHnbpa8aL6TZciRixYb0G23R0Yu2xXxeiPQGYUgcAUHOch3a07dmBJkq4h6rGoxJyN7wb+GlClKODx9dLPM3yCoKCTsiBFB8Z1utFQYi7kdGLlhKXIUTFEoc61rKifWwNG7kBTitjE01y6oN08np1/ILLJSY9V0yC1L0kWehpbXWy6jpo0UVOl8DgJ+NdGR/BNRoKMV0NcDtgtis3ngm7jj0R48bqD5fQBrwYjPaH378p7x0803bWCY883PZ31C02/uBy5wc4SeDIMek1rTmCB6TbYA6SFBPT6EvYpBMjwd8Ep7WdWip6paK3g/oUqn31s1G7WkAzQIpKkRUldjG8Gp3z9huuqJEeRm7TFN0XHIDp9FRkwRj0Atq8t7rmYrf1R1eqdEhxZA26JrHN/7U1mMk3d1OI/5gsnrVm2+5W2WEU71dM2CngypxfFcsgMuc4oXBEIuwTXKaH0Om9ApixSvl/UyCys27ktT83M/SOXf+YTdUtNYXYAqgRSGtMvqeLk01stCDFE7y0APFsLEuWAngeq8amo/4v7vQ+wvLCqulGNT4ll145dF6e0p3wAdEWKcvgVL7w/eazmQtV9SY9rbpZfvfUqIanVi6060pT75UIotXNeY/Kz30iQJ1kyRzGDmbH+K8h1BjEGUnomIzyXNKtJkBPWp4AfOPNqlSauFM8nQnPLLMatvLAaXlhLVlxLqgKmwQovz9
  template:
    metadata:
      creationTimestamp: null
      name: discord-webhook-secret
      namespace: {{ required "A namespace must be provided" .Values.namespace }}
    type: Opaque
